In [13]:
import torch
from torch import nn

In [74]:
# Build the model
model = nn.Linear(in_features=1, out_features=1)
loss_fn = nn.MSELoss()
nn.L1Loss
nn.HuberLoss
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)
print(list(model.parameters()))
#model.weight = nn.Parameter(torch.tensor([[0.]]))
#model.bias = nn.Parameter(torch.tensor([0.]))
print(list(model.parameters()))

[Parameter containing:
tensor([[0.8506]], requires_grad=True), Parameter containing:
tensor([-0.4025], requires_grad=True)]
[Parameter containing:
tensor([[0.8506]], requires_grad=True), Parameter containing:
tensor([-0.4025], requires_grad=True)]


In [75]:
# Define my input and ouput
#x = torch.tensor([[1.0],[2.0],[3.0],[4.0],[5.0]])
x = torch.tensor([[0.0],[1.0],[2.0],[3.0],[4.0]])
y = torch.tensor([[1.0],[3.0],[5.0],[7.0],[9.0]])
x.shape

torch.Size([5, 1])

In [76]:
## Train the neural network
# Do a forward pass and predict the output
for epoch in range(1000):
    #model.zero_grad()
    y_pred = model(x)
    #print(y_pred)
    # compute the loss
    loss = loss_fn(y_pred, y)
    print(loss)

    # optimize the values of w and b
    model.zero_grad()
    loss.backward()
    optimizer.step()

print(list(model.parameters()))

tensor(16.3429, grad_fn=<MseLossBackward0>)
tensor(522.7743, grad_fn=<MseLossBackward0>)
tensor(16990.0645, grad_fn=<MseLossBackward0>)
tensor(552307.6875, grad_fn=<MseLossBackward0>)
tensor(17954316., grad_fn=<MseLossBackward0>)
tensor(5.8366e+08, grad_fn=<MseLossBackward0>)
tensor(1.8973e+10, grad_fn=<MseLossBackward0>)
tensor(6.1678e+11, grad_fn=<MseLossBackward0>)
tensor(2.0050e+13, grad_fn=<MseLossBackward0>)
tensor(6.5179e+14, grad_fn=<MseLossBackward0>)
tensor(2.1188e+16, grad_fn=<MseLossBackward0>)
tensor(6.8878e+17, grad_fn=<MseLossBackward0>)
tensor(2.2391e+19, grad_fn=<MseLossBackward0>)
tensor(7.2788e+20, grad_fn=<MseLossBackward0>)
tensor(2.3662e+22, grad_fn=<MseLossBackward0>)
tensor(7.6919e+23, grad_fn=<MseLossBackward0>)
tensor(2.5005e+25, grad_fn=<MseLossBackward0>)
tensor(8.1285e+26, grad_fn=<MseLossBackward0>)
tensor(2.6424e+28, grad_fn=<MseLossBackward0>)
tensor(8.5898e+29, grad_fn=<MseLossBackward0>)
tensor(2.7924e+31, grad_fn=<MseLossBackward0>)
tensor(9.0774e+32,